name: Sabyasachi's Automated Workflow
on:
  # push:
  #   branch: [ master ]
  schedule:
    - cron: "0 0 */ * *"
  workflow_dispatch:
jobs:
  release:
    name: Profile Views Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          token: ${{ secrets.INSIGHTS_TOKEN }}
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Update Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.17.0
      - name: Install Requests
        run: |
          pip install requests
      - name: Setting Up GitPush
        run: |
          git config user.email "yoboy907@gmail.com"
          git config user.name "Sabyasachi Seal"
        env:
          key: ${{ secrets.key }}
      - name: Update Repolist
        run: |
          python repolist.py
        env:
          key: ${{ secrets.key }}
      - name: Run the Counter
        uses: Sabyasachi-Seal/ViewsCounterAction@StableV6
        env:
          INSIGHTS_TOKEN: ${{ secrets.INSIGHTS_TOKEN }}
