name: Sabyasachi's Automated Workflow
on:
  # push:
  #   branch: [ master ]
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:
jobs:
  release:
    name: Profile Views Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          token: ${{ secrets.INSIGHTS_TOKEN }}
      - name: Update Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.17.0
      - name: Update Repolist
        uses: python3 repolist.py
      - name: Run the Counter
        uses: Sabyasachi-Seal/github-profile-views-counter-action@StableV6
        env:
          INSIGHTS_TOKEN: ${{ secrets.INSIGHTS_TOKEN }}
